package maman16.trivianet.triviacommon;

public enum TriviaMessageType {
    CLIENT_MESSAGE_REQUEST_QUESTION,
    CLIENT_MESSAGE_SUBMIT_ANSWER,
    CLIENT_MESSAGE_END_SESSION,
    CLIENT_MESSAGE_START_SESSION,
    CLIENT_MESSAGE_HAS_UNUSED_QUESTIONS,
    SERVER_MESSAGE_NO_MORE_QUESTIONS,
    SERVER_MESSAGE_RESPONSE_OK,
    SERVER_MESSAGE_RESPONSE_ERROR,
    SERVER_MESSAGE_PROVIDE_QUESTION,
    SERVER_MESSAGE_RESPONSE_YES,
    SERVER_MESSAGE_RESPONSE_NO
}
