package maman16.trivianet.triviacommon;

public enum TriviaMessageType {
    CLIENT_MESSAGE_REQUEST_QUESTION,
    SERVER_MESSAGE_PROVIDE_QUESTION,
    CLIENT_MESSAGE_SUBMIT_ANSWER,
    CLIENT_MESSAGE_END_SESSION,
    CLIENT_MESSAGE_START_SESSION
}
